### PR TITLE
Fix simapi syntax and test bugs

### PR DESCRIPTION
**Pull request by lrennels**

### CODE REVIEW

**Comment by lrennels** [comment]
@AlexandrePavlov I did notice here that the tests in the 
```
@testset "MimiDICE2016-integration" begin
```
don't pass in terms of matching the validation data, but I'm not sure if those are just relics of how we tested before or tests that you were using to validate your results?

**Comment by AlexandrePavlov** [comment]
Yes, that bit is a relic of MimiDICE2013. I have not touched upon the code much because I was not sufficiently familiar with it. Feel free to correct the code if there is anything to correct. I know for a fact every test between line 1 and line 69 and between line 116 and line 155 pass, however.

**Comment by lrennels** [comment]
I see!  I don’t think the code is wrong right now, I fixed an underscore issue, but the tests fail since the values you produce don’t match the validation data files.  If those aren’t the right files for DICE2016 we should probably just delete them and the testing code?

**Comment by AlexandrePavlov** [comment]
I'm not sure, maybe the files are wrong. I personally don't need this part of the code and have no problem deleting it, but I don't know if the omission might be an issue for others.

**Pull request merged**
