### PR TITLE
getdicegams

### PR DESCRIPTION
**Pull request by lrennels**
I noticed that the `getdicegamsparameters` function was not quite completed, and thus the `getdicegams` function wasn't working. I have updated it so that values not available in the GAMS input file pull directly from Excel so that it will run. That said **we do not test `getdicegams`, we only test `getdiceexcel`**, thus it is unclear to me how to know if this was the right way to do it, and whether we should be exporting `getdicegams`, or even have that function?

### CODE REVIEW

**Comment by lrennels** [comment]
@AlexandrePavlov do you know where the Excel file `DICE2016_IAMF_Parameters.xlsx` came from? I noticed that I think only something like two values (`:fco22x` and `:tocean0`) differ from the model, the latter by exactly 10x.

**Comment by AlexandrePavlov** [comment]
@lrennels I believe the DICE2016_IAMF_Parameters.xlsx file is a modified version of its DICE2013 counterpart with updated parameters. The other file in the data folder comes from Nordhaus' website.

**Comment by lrennels** [comment]
@AlexandrePavlov Got it, so was that modified by you by hand from the DICE2013 Excel Model? I'm just wondering if it's meant to be a carbon copy of the DICE2016 Excel model parameters, in which case I would probably just remove the `getdicegams` function until we have one that has a dependable difference from the Excel model.

**Comment by AlexandrePavlov** [comment]
@Irennels Yes, the parameters in the two files are meant to be the same.

**Comment by AlexandrePavlov** [comment]
@lrennels Yes, the parameters in the two files are meant to be the same.

**Comment by lrennels** [comment]
@AlexandrePavlov  @davidanthoff  Perfect, how do we feel about me removing the file and function for now then just for clarity purposes?  As I work if I find everything we need to replicate the gams model I can add a new PR to put that option in to the repository.

**Comment by lrennels** [comment]
@AlexandrePavlov actually don't merge yet, I think I may have found the GAMS version of 2016R

**Pull request merged**
